server:
  port: 8001

spring:
  application:
    name: gateway8001
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fun-provider
          uri: lb://fun-provider
          predicates:
            - Path=/**
    circuitbreaker:
      resilience4j:
        enabled: false
        instances:
          backendA:
            baseConfig: default
            waitDurationInOpenState: 5000
            failureRateThreshold: 20



