server:
  port: 8083

spring:
  application:
    name: fun-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        hostname: localhost
